/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package Views;

import Models.ChiTietDep;
import Models.HoaDon;
import Models.HoaDonChiTiet;
import Models.KhachHang;
import Models.KhuyenMai;
import Models.NguoiDung;
import Services.IChiTietDepService;
import Services.IHoaDonChiTietService;
import Services.IHoaDonService;
import Services.implement.ChiTietDepService;
import Services.implement.HoaDonChiTietService;
import Services.implement.HoaDonService;
import java.math.BigDecimal;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.List;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.RootPaneContainer;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Admin
 */
public class BanHangPanel extends javax.swing.JPanel {

    int index = -1;
    int indexHd = -1;
    IHoaDonService hdService;
    IHoaDonChiTietService hdCtService;
    IChiTietDepService ctdService;
    DefaultTableModel tblModelHoaDon;
    DefaultTableModel tblModelGioHang;
    DefaultTableModel tblModelSanPham;
    KhachHang khachHang = null;
    NguoiDung nguoiDung = null;
    KhuyenMai khuyenMai = null;
    SimpleDateFormat sdf = new SimpleDateFormat("dd-MM-yyyy");

    public BanHangPanel() {
        initComponents();

        hdService = new HoaDonService();
        hdCtService = new HoaDonChiTietService();
        ctdService = new ChiTietDepService();

        getModelTable();

        loadTableHoaDon(hdService.getAllByObj("", 0));
        loadTableSanPham(ctdService.getAllByObj(0, ""));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    public void getModelTable() {
        tblModelHoaDon = (DefaultTableModel) tblHoaDon.getModel();
        tblModelGioHang = (DefaultTableModel) tblGioHang.getModel();
        tblModelSanPham = (DefaultTableModel) tblSanPham.getModel();
    }

    public void loadTableHoaDon(List<HoaDon> lst) {
        int i = 0;
        tblModelHoaDon.setRowCount(0);
        for (HoaDon hd : lst) {
            tblModelHoaDon.addRow(new Object[]{
                ++i,
                hd.getMa(),
                hd.getNguoiDung() == null ? "Nhân Viên Ảo" : hd.getNguoiDung(),
                hd.getKhachHang() == null ? "Khách Hàng Ảo" : hd.getKhachHang(),
                sdf.format(hd.getNgayTao()),
                hd.getTinhTrang()
            });
        }
    }

    public void loadTableSanPham(List<ChiTietDep> lst) {
        int i = 0;
        tblModelSanPham.setRowCount(0);
        for (ChiTietDep ctd : lst) {
            tblModelSanPham.addRow(new Object[]{
                ++i,
                ctd.getDep().getMa(),
                ctd.getDep().getTen(),
                ctd.getLoaiDep(),
                ctd.getSize(),
                ctd.getNsx(),
                ctd.getSoLuong(),
                ctd.getGiaBan()
            });
        }

    }

    public void loadTableGioHang(List<HoaDonChiTiet> lst) {
        int i = 0;
        tblModelGioHang.setRowCount(0);
        for (HoaDonChiTiet hdct : lst) {
            tblModelGioHang.addRow(new Object[]{
                ++i,
                hdct.getChiTietDep().getDep().getMa(),
                hdct.getChiTietDep().getDep().getTen(),
                hdct.getSoLuong(),
                hdct.getDonGia(),
                hdct.getSoLuong() * hdct.getDonGia().doubleValue()
            });
        }
    }

    public void clickHoaDon() {
        indexHd = tblHoaDon.getSelectedRow();

        String ma = tblHoaDon.getValueAt(indexHd, 1).toString();

        loadTableGioHang(hdCtService.getAllByMa(ma));

        txtMaHD.setText(ma);
        double tongTien = 0;
        txtTongTien.setText(String.valueOf(tongTien));

        for (int i = 0; i < tblGioHang.getRowCount(); i++) {
            double thanhTien = Double.parseDouble(tblGioHang.getValueAt(i, 5).toString());
            tongTien = tongTien + thanhTien;
        }
        txtTongTien.setText(String.valueOf(tongTien));

    }

    public void clickAddSanPham() {
        int indexHD = tblHoaDon.getSelectedRow();
        int indexSp = tblSanPham.getSelectedRow();

        String maHd = tblHoaDon.getValueAt(indexHD, 1).toString();

        HoaDon hd = hdService.getObj(maHd);

        String idCtd = tblSanPham.getValueAt(indexSp, 0).toString();
        ChiTietDep ctd = ctdService.getAllByObj(0, "").get(indexSp);

        String soLuong = JOptionPane.showInputDialog(this, "Nhập Số Lượng Muốn Thêm ?");
        if (soLuong == null) {
            return;
        }
        HoaDonChiTiet hdct = new HoaDonChiTiet();
        hdct.setChiTietDep(ctd);
        hdct.setHoaDon(hd);
        hdct.setNgaySua(new Date());
        hdct.setNgayTao(new Date());
        hdct.setSoLuong(Integer.valueOf(soLuong));
        hdct.setTinhTrang(0);
        hdct.setDonGia(ctd.getGiaBan());
        ctd.setSoLuong(ctd.getSoLuong() - Integer.valueOf(soLuong));

        ctdService.save(ctd);
        hdCtService.save(hdct);

        loadTableGioHang(hdCtService.getAllByMa(maHd));
        loadTableSanPham(ctdService.getAllByObj(0, ""));

//        HoaDonChiTiet hdct = hdCtService.getObj(hd.getId(), ctd.getId());
    }

    public void clickGioHang() {
        String soLuong;
        int indexHd = tblHoaDon.getSelectedRow();
        int indexGh = tblGioHang.getSelectedRow();
        String maHd = tblHoaDon.getValueAt(indexHd, 1).toString();
        String maSp = tblGioHang.getValueAt(indexGh, 1).toString();
        HoaDonChiTiet hdct = hdCtService.getAllByMa(maHd).get(indexGh);
        hdCtService.delete(hdct);
        loadTableGioHang(hdCtService.getAllByMa(maHd));

//        ChiTietDep ctd = ctdService.getObj(maSp);
//        soLuong = JOptionPane.showInputDialog(this, "Nhap so luong");
//        if (soLuong == null) {
//            return;
//        }
//
//        if (soLuong == "0") {
//            hdCtService.delete(hdct);
//            ctd.setSoLuong(ctd.getSoLuong() + hdct.getSoLuong());
//        } else {
//            hdct.setSoLuong(Integer.valueOf(soLuong));
//            hdCtService.save(hdct);
//            ctd.setSoLuong(ctd.getSoLuong() - Integer.valueOf(soLuong));
//        }
//        loadTableGioHang(hdCtService.getAllByMa(maHd));
//        loadTableSanPham(ctdService.getAllByObj(0, ""));
    }

    public void chonKhachHang() {
        KHDlog hkDlog = new KHDlog(new javax.swing.JFrame(), true);
        hkDlog.setVisible(true);

        khachHang = hkDlog.getKhachHang();
        txtMaKh.setText(khachHang.getMa());
        txtTenKh.setText(khachHang.getTen());
        lblDiemTichLy.setText("Điểm tích lỹ: " + khachHang.getDiemTichLy());

    }

    public void taoHoaDon() {
        int chk = JOptionPane.showConfirmDialog(this, "Bạn Chắc Muốn Tạo Hóa Đơn");
        if (chk == JOptionPane.YES_OPTION) {
            HoaDon hd = new HoaDon();
            for (int i = 0; i < hdService.getLst().size() + 1; i++) {
                String maHd = "HD00" + i;
                if (hdService.getObj(maHd) == null) {
                    hd.setMa(maHd);
                    break;
                }
            }

            hd.setNgayTao(new Date());
            hd.setNgaySua(new Date());
            hd.setTinhTrang(0);

            hd.setKhachHang(khachHang);
            hd.setNguoiDung(nguoiDung);

            hd.setTongTien(new BigDecimal(0));
            hd.setThanhTien(new BigDecimal(0));
            if (hdService.save(hd)) {
                JOptionPane.showMessageDialog(this, "Tạo Hóa Đơn Thành Công");
            } else {
                JOptionPane.showMessageDialog(this, "Tạo Hóa Đơn Thất Bại");
            }

            loadTableHoaDon(hdService.getAllByObj("", 0));

        }

    }

    public void chonKhuyenMai() {
        KhuyenMaiDlog kmDlog = new KhuyenMaiDlog(new javax.swing.JFrame(), true);
        kmDlog.setVisible(true);

        khuyenMai = kmDlog.getKhuyenMai();
        txtMaKm.setText(khuyenMai.getMa());
        txtTenKm.setText(khuyenMai.getTen());
        tienThanhToan();
    }

    public void tienThanhToan() {
        double tongTien = Double.valueOf(txtTongTien.getText());
        Double giaGiam = 0.0;
        if (txtTongTien.getText().trim().length() == 0) {
            return;
        }
        if (khuyenMai != null) {
            giaGiam = tongTien * this.khuyenMai.getPhanTramGiam() / 100;
        }
        if (chkTichLy.isSelected() == true) {
            if (khachHang != null) {
                giaGiam = giaGiam + (Double.valueOf(khachHang.getDiemTichLy())*1000);
            }
        }

        txtGiamGia.setText(String.valueOf(giaGiam));
        txtThanhTien.setText(String.valueOf(tongTien - giaGiam));
        tienThua();

    }

    public void tienThua() {
        String tienKhDua = txtTienKhachDua.getText();
        String thanhTien = txtThanhTien.getText();
        Double tienThua = 0.0;
        if (tienKhDua.trim().length() == 0) {
            txtTienThua.setText("");
            return;
        }
        try {
            tienThua = Double.valueOf(tienKhDua) - Double.valueOf(thanhTien);
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Vui lòng nhập số");
            e.printStackTrace();
        }
        txtTienThua.setText(String.valueOf(tienThua));

    }

    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        table1 = new swing.Table();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblHoaDon = new javax.swing.JTable();
        txtTimKiemHoaDon = new textfield.TextField();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblGioHang = new javax.swing.JTable();
        button7 = new Utilities.raven.textfield.Button();
        button8 = new Utilities.raven.textfield.Button();
        jPanel3 = new javax.swing.JPanel();
        jPanel6 = new javax.swing.JPanel();
        txtMaKh = new textfield.TextField();
        txtTenKh = new textfield.TextField();
        btnTaoHD = new swing.Button();
        btnChonKH = new swing.Button();
        btnKhAo = new swing.Button();
        jPanel7 = new javax.swing.JPanel();
        txtMaHD = new textfield.TextField();
        txtGiamGia = new textfield.TextField();
        txtThanhTien = new textfield.TextField();
        txtTienKhachDua = new textfield.TextField();
        txtTienThua = new textfield.TextField();
        txtTenKm = new textfield.TextField();
        btnThanhToan = new swing.Button();
        txtMaKm = new textfield.TextField();
        txtTongTien = new textfield.TextField();
        lblDiemTichLy = new javax.swing.JLabel();
        chkTichLy = new checkbox.JCheckBoxCustom();
        btnThemKm = new swing.Button();
        btnXoaKm = new swing.Button();
        jPanel4 = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        tblSanPham = new javax.swing.JTable();
        txtTimKiemSanPham = new textfield.TextField();
        jPanel5 = new javax.swing.JPanel();

        setBackground(new java.awt.Color(255, 255, 255));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204)), "Hóa Đơn"));

        tblHoaDon.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "STT", "Mã", "Nhân Viên", "Khách Hàng", "Ngày Tạo", "Trạng Thái"
            }
        ));
        tblHoaDon.setGridColor(new java.awt.Color(255, 255, 255));
        tblHoaDon.setSelectionBackground(new java.awt.Color(0, 204, 255));
        tblHoaDon.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblHoaDonMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblHoaDon);

        txtTimKiemHoaDon.setDisabledTextColor(new java.awt.Color(46, 84, 133));
        txtTimKiemHoaDon.setFont(new java.awt.Font("Segoe UI Variable", 0, 12)); // NOI18N
        txtTimKiemHoaDon.setLabelText("Tìm Hóa Đơn");
        txtTimKiemHoaDon.setLineColor(new java.awt.Color(23, 143, 246));
        txtTimKiemHoaDon.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTimKiemHoaDonActionPerformed(evt);
            }
        });
        txtTimKiemHoaDon.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtTimKiemHoaDonKeyReleased(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtTimKiemHoaDon, javax.swing.GroupLayout.PREFERRED_SIZE, 270, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 510, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtTimKiemHoaDon, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204)), "Giỏ Hàng"));

        tblGioHang.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "STT", "Mã SP", "Tên SP", "Số Lượng", "Đơn Giá", "Thành Tiền"
            }
        ));
        tblGioHang.setSelectionBackground(new java.awt.Color(0, 204, 255));
        tblGioHang.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblGioHangMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tblGioHang);

        button7.setBackground(new java.awt.Color(51, 102, 255));
        button7.setForeground(new java.awt.Color(255, 255, 255));
        button7.setText("Xóa");
        button7.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N

        button8.setBackground(new java.awt.Color(51, 102, 255));
        button8.setForeground(new java.awt.Color(255, 255, 255));
        button8.setText("Xóa Tất Cả");
        button8.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 639, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(button8, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(button7, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(105, Short.MAX_VALUE))
        );

        jPanel2Layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {button7, button8});

        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(38, 38, 38)
                        .addComponent(button7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(button8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 183, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204)), "Thanh Toán"));

        txtMaKh.setLabelText("Mã Khách Hàng");

        txtTenKh.setLabelText("Tên Khách Hàng");

        btnTaoHD.setBackground(new java.awt.Color(0, 153, 255));
        btnTaoHD.setForeground(new java.awt.Color(255, 255, 255));
        btnTaoHD.setText("Tạo Hóa Đơn");
        btnTaoHD.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnTaoHD.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTaoHDActionPerformed(evt);
            }
        });

        btnChonKH.setBackground(new java.awt.Color(0, 153, 255));
        btnChonKH.setForeground(new java.awt.Color(255, 255, 255));
        btnChonKH.setText("Chọn KH");
        btnChonKH.setToolTipText("");
        btnChonKH.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnChonKH.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnChonKHActionPerformed(evt);
            }
        });

        btnKhAo.setBackground(new java.awt.Color(0, 153, 255));
        btnKhAo.setForeground(new java.awt.Color(255, 255, 255));
        btnKhAo.setText("KH Ảo");
        btnKhAo.setToolTipText("");
        btnKhAo.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnKhAo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnKhAoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addComponent(btnTaoHD, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addContainerGap())
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(txtTenKh, javax.swing.GroupLayout.DEFAULT_SIZE, 210, Short.MAX_VALUE)
                            .addComponent(txtMaKh, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnKhAo, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnChonKH, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(13, 13, 13))))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtMaKh, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnChonKH, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtTenKh, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnKhAo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 34, Short.MAX_VALUE)
                .addComponent(btnTaoHD, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        txtMaHD.setLabelText("Mã Hóa Đơn");

        txtGiamGia.setLabelText("Giảm Giá");

        txtThanhTien.setLabelText("Thành Tiền");

        txtTienKhachDua.setLabelText("Tiền Khách Đưa");
        txtTienKhachDua.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtTienKhachDuaKeyReleased(evt);
            }
        });

        txtTienThua.setLabelText("Tiền Thừa");

        txtTenKm.setLabelText("Tên Khuyến Mãi");

        btnThanhToan.setBackground(new java.awt.Color(51, 153, 255));
        btnThanhToan.setForeground(new java.awt.Color(255, 255, 255));
        btnThanhToan.setText("Thanh Toán");
        btnThanhToan.setToolTipText("");
        btnThanhToan.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N

        txtMaKm.setLabelText("Mã Khuyến Mãi");

        txtTongTien.setLabelText("Tổng Tiền");

        lblDiemTichLy.setText("Điểm tích lỹ: 0");

        chkTichLy.setText("Sử dụng ?");
        chkTichLy.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chkTichLyActionPerformed(evt);
            }
        });

        btnThemKm.setBackground(new java.awt.Color(51, 153, 255));
        btnThemKm.setForeground(new java.awt.Color(255, 255, 255));
        btnThemKm.setText("Thêm KM");
        btnThemKm.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnThemKm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThemKmActionPerformed(evt);
            }
        });

        btnXoaKm.setBackground(new java.awt.Color(51, 153, 255));
        btnXoaKm.setForeground(new java.awt.Color(255, 255, 255));
        btnXoaKm.setText("Xóa");
        btnXoaKm.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnXoaKm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnXoaKmActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnThanhToan, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(txtTienKhachDua, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 182, Short.MAX_VALUE)
                            .addComponent(txtThanhTien, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(txtGiamGia, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(txtTongTien, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(txtMaHD, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(txtTienThua, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(36, 36, 36)
                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel7Layout.createSequentialGroup()
                                .addComponent(btnThemKm, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(btnXoaKm, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(lblDiemTichLy)
                            .addComponent(chkTichLy, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(txtTenKm, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 182, Short.MAX_VALUE)
                                .addComponent(txtMaKm, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtMaHD, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtMaKm, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtTenKm, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtTongTien, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(16, 16, 16)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addComponent(txtGiamGia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtThanhTien, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnThemKm, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnXoaKm, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(txtTienKhachDua, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addComponent(lblDiemTichLy)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(chkTichLy, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addComponent(txtTienThua, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(32, 32, 32)
                .addComponent(btnThanhToan, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));
        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204)), "Sản Phẩm"));

        tblSanPham.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "STT", "Mã", "Tên", "Loại", "Size", "NSX", "Số Lượng Tồn", "Đơn Giá"
            }
        ));
        tblSanPham.setSelectionBackground(new java.awt.Color(51, 204, 255));
        tblSanPham.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblSanPhamMouseClicked(evt);
            }
        });
        jScrollPane3.setViewportView(tblSanPham);

        txtTimKiemSanPham.setLabelText("Tìm Kiếm");
        txtTimKiemSanPham.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtTimKiemSanPhamKeyReleased(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane3)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(txtTimKiemSanPham, javax.swing.GroupLayout.PREFERRED_SIZE, 258, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(txtTimKiemSanPham, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 217, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(50, 50, 50))
        );

        jPanel5.setBackground(new java.awt.Color(255, 255, 255));
        jPanel5.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204)), "QR"));

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 204, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jPanel3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, 313, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void txtTimKiemHoaDonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTimKiemHoaDonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTimKiemHoaDonActionPerformed

    private void btnTaoHDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTaoHDActionPerformed
        taoHoaDon();
    }//GEN-LAST:event_btnTaoHDActionPerformed

    private void chkTichLyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chkTichLyActionPerformed
        tienThanhToan();
    }//GEN-LAST:event_chkTichLyActionPerformed

    private void btnThemKmActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThemKmActionPerformed
        chonKhuyenMai();
    }//GEN-LAST:event_btnThemKmActionPerformed

    private void btnChonKHActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnChonKHActionPerformed
        chonKhachHang();
    }//GEN-LAST:event_btnChonKHActionPerformed

    private void tblHoaDonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblHoaDonMouseClicked
        clickHoaDon();
        tienThanhToan();
    }//GEN-LAST:event_tblHoaDonMouseClicked

    private void tblSanPhamMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblSanPhamMouseClicked
        clickAddSanPham();
    }//GEN-LAST:event_tblSanPhamMouseClicked

    private void tblGioHangMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblGioHangMouseClicked
        clickGioHang();
    }//GEN-LAST:event_tblGioHangMouseClicked

    private void txtTimKiemSanPhamKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtTimKiemSanPhamKeyReleased
        loadTableSanPham(ctdService.getAllByObj(0, txtTimKiemSanPham.getText()));
    }//GEN-LAST:event_txtTimKiemSanPhamKeyReleased

    private void txtTimKiemHoaDonKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtTimKiemHoaDonKeyReleased
        loadTableHoaDon(hdService.getAllByObj(txtTimKiemHoaDon.getText(), 0));
    }//GEN-LAST:event_txtTimKiemHoaDonKeyReleased

    private void btnKhAoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnKhAoActionPerformed
        this.khachHang = null;
        txtMaKh.setText("Khách Hàng Ảo");
        txtTenKh.setText("Khách Hàng Ảo");
    }//GEN-LAST:event_btnKhAoActionPerformed

    private void btnXoaKmActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnXoaKmActionPerformed
        this.khuyenMai = null;
        txtMaKm.setText("");
        txtTenKm.setText("");
        tienThanhToan();
    }//GEN-LAST:event_btnXoaKmActionPerformed

    private void txtTienKhachDuaKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtTienKhachDuaKeyReleased
        tienThua();
    }//GEN-LAST:event_txtTienKhachDuaKeyReleased


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private swing.Button btnChonKH;
    private swing.Button btnKhAo;
    private swing.Button btnTaoHD;
    private swing.Button btnThanhToan;
    private swing.Button btnThemKm;
    private swing.Button btnXoaKm;
    private Utilities.raven.textfield.Button button7;
    private Utilities.raven.textfield.Button button8;
    private checkbox.JCheckBoxCustom chkTichLy;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JLabel lblDiemTichLy;
    private swing.Table table1;
    private javax.swing.JTable tblGioHang;
    private javax.swing.JTable tblHoaDon;
    private javax.swing.JTable tblSanPham;
    private textfield.TextField txtGiamGia;
    private textfield.TextField txtMaHD;
    private textfield.TextField txtMaKh;
    private textfield.TextField txtMaKm;
    private textfield.TextField txtTenKh;
    private textfield.TextField txtTenKm;
    private textfield.TextField txtThanhTien;
    private textfield.TextField txtTienKhachDua;
    private textfield.TextField txtTienThua;
    private textfield.TextField txtTimKiemHoaDon;
    private textfield.TextField txtTimKiemSanPham;
    private textfield.TextField txtTongTien;
    // End of variables declaration//GEN-END:variables
}
