/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package Views;

import Models.ChatLieu;
import Models.ChiTietDep;
import Models.LoaiDep;
import Models.MauSac;
import Models.Nsx;
import Models.Size;
import Services.IChatLieuService;
import Services.IChiTietDepService;
import Services.ILoaiDepService;
import Services.IMauSacService;
import Services.INsxService;
import Services.ISizeService;
import Services.implement.ChatLieuService;
import Services.implement.ChiTietDepService;
import Services.implement.LoaiDepService;
import Services.implement.MauSacService;
import Services.implement.NsxService;
import Services.implement.SizeService;
import java.util.List;
import javax.swing.DefaultComboBoxModel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Admin
 */
public class SanPhamPanel extends javax.swing.JPanel {

    int index = -1;
    IChatLieuService clService;
    ISizeService sizeService;
    ILoaiDepService ldService;
    IMauSacService msService;
    INsxService nsxService;
    IChiTietDepService ctdService;

    DefaultTableModel tblModelSp;

    public SanPhamPanel() {
        initComponents();

        clService = new ChatLieuService();
        sizeService = new SizeService();
        ldService = new LoaiDepService();
        msService = new MauSacService();
        nsxService = new NsxService();
        ctdService = new ChiTietDepService();

        tblModelSp = (DefaultTableModel) tblSanPham.getModel();

        intCbo();
        loadTableSanPham(ctdService.getLstByTen(txtTimKiemSp.getText()));

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    public void intCbo() {
        initCboChatLieu();
        initCboSize();
        initCboLoai();
        initCboMauSac();
        initCboNsx();
    }

    public void initCboChatLieu() {
        DefaultComboBoxModel<ChatLieu> boxModel = new DefaultComboBoxModel<>();
        cboChatLieu.removeAllItems();
        cboChatLieu.setModel((DefaultComboBoxModel) boxModel);

        for (ChatLieu chatLieu : clService.getLst()) {
            boxModel.addElement(chatLieu);
        }

    }

    public void initCboSize() {
        DefaultComboBoxModel<Size> boxModel = new DefaultComboBoxModel<>();
        cboSize.removeAllItems();
        cboSize.setModel((DefaultComboBoxModel) boxModel);

        for (Size size : sizeService.getLst()) {
            boxModel.addElement(size);
        }

    }

    public void initCboLoai() {
        DefaultComboBoxModel<LoaiDep> boxModel = new DefaultComboBoxModel<>();
        cboLoai.removeAllItems();
        cboLoai.setModel((DefaultComboBoxModel) boxModel);

        for (LoaiDep ld : ldService.getLst()) {
            boxModel.addElement(ld);
        }

    }

    public void initCboMauSac() {
        DefaultComboBoxModel<MauSac> boxModel = new DefaultComboBoxModel<>();
        cboMauSac.removeAllItems();
        cboMauSac.setModel((DefaultComboBoxModel) boxModel);

        for (MauSac ms : msService.getLst()) {
            boxModel.addElement(ms);
        }

    }

    public void initCboNsx() {
        DefaultComboBoxModel<Nsx> boxModel = new DefaultComboBoxModel<>();
        cboNsx.removeAllItems();
        cboNsx.setModel((DefaultComboBoxModel) boxModel);

        for (Nsx nsx : nsxService.getLst()) {
            boxModel.addElement(nsx);
        }

    }

    public void loadTableSanPham(List<ChiTietDep> lst) {
        int i = 0;
        tblModelSp.setRowCount(0);

        for (ChiTietDep ctd : lst) {
            tblModelSp.addRow(new Object[]{
                ++i,
                ctd.getDep().getMa(),
                ctd.getDep().getTen(),
                ctd.getLoaiDep().getTen(),
                ctd.getSize().getKichCo(),
                ctd.getChatLieu().getTen(),
                ctd.getMauSac().getMauSac(),
                ctd.getNsx().getTen(),
                ctd.getSoLuong(),
                ctd.getGiaNhap(),
                ctd.getGiaBan(),
                ctd.getMoTa(),
                ctd.getNgayTao(),
                ctd.getTinhTrang() == 0 ? "Ðang Kinh Doanh" : "Ngừng Kinh Doanh"
            });
        }
    }

    public void clickTableSanPham() {
        index = tblSanPham.getSelectedRow();
        List<ChiTietDep> lst = ctdService.getLstByTen(txtTimKiemSp.getText());

        String ma = tblModelSp.getValueAt(index, 1).toString();
        String ten = tblModelSp.getValueAt(index, 2).toString();
        Object loai = tblModelSp.getValueAt(index, 3);
        Object size = tblModelSp.getValueAt(index, 4);
        Object chatLieu = tblModelSp.getValueAt(index, 5);
        Object mauSac = tblModelSp.getValueAt(index, 6);
        Object nsx = tblModelSp.getValueAt(index, 7);
        String soLuong = tblModelSp.getValueAt(index, 8).toString();
        String giaNhap = tblModelSp.getValueAt(index, 9).toString();
        String giaBan = tblModelSp.getValueAt(index, 10).toString();
//        String moTa = tblModelSp.getValueAt(index, 12).toString();
        String trangThai = tblModelSp.getValueAt(index, 13).toString();

        txtMaSp.setText(ma);
        txtTenSp.setText(ten);
        txtSoLuong.setText(soLuong);
        txtGiaNhap.setText(giaNhap);
        txtGiaBan.setText(giaBan);
//        txtMoTa.setText(moTa);

        if (trangThai.equalsIgnoreCase("Ðang Kinh Doanh")) {
            rdoDangKD.setSelected(true);
        } else {
            rdoNgungKD.setSelected(true);
        }
        
        int loaiCount = cboLoai.getItemCount();
        for (int i = 0; i < loaiCount; i++) {
            Object l = cboLoai.getItemAt(i);
            if (l.toString().equals(loai.toString())) {
                cboLoai.setSelectedIndex(i);
                break;
            }
        }
        
        int sizeCount = cboSize.getItemCount();
        for (int i = 0; i < sizeCount; i++) {
            Object s = cboSize.getItemAt(i);
            if (s.toString().equals(size.toString())) {
                cboSize.setSelectedIndex(i);
                break;
            }
        }
        int chatLieuCount = cboChatLieu.getItemCount();
        for (int i = 0; i < chatLieuCount; i++) {
            Object cl = cboChatLieu.getItemAt(i);
            if (cl.toString().equals(chatLieu.toString())) {
                cboChatLieu.setSelectedIndex(i);
                break;
            }
        }
        int mauSacCount = cboMauSac.getItemCount();
        for (int i = 0; i < mauSacCount; i++) {
            Object ms = cboMauSac.getItemAt(i);
            if (ms.toString().equals(mauSac.toString())) {
                cboMauSac.setSelectedIndex(i);
                break;
            }
        }
        int nsxCount = cboNsx.getItemCount();
        for (int i = 0; i < nsxCount; i++) {
            Object n = cboNsx.getItemAt(i);
            if (n.toString().equals(nsx)) {
                cboNsx.setSelectedIndex(i);
                break;
            }
        }

    }

    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jPanel1 = new javax.swing.JPanel();
        txtMaSp = new textfield.TextField();
        txtTenSp = new textfield.TextField();
        txtMaVach = new textfield.TextField();
        txtSoLuong = new textfield.TextField();
        txtGiaNhap = new textfield.TextField();
        txtGiaBan = new textfield.TextField();
        cboLoai = new combobox.Combobox();
        cboSize = new combobox.Combobox();
        cboChatLieu = new combobox.Combobox();
        cboNsx = new combobox.Combobox();
        cboMauSac = new combobox.Combobox();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        txtMoTa = new textfield.TextField();
        rdoDangKD = new radio_button.RadioButtonCustom();
        rdoNgungKD = new radio_button.RadioButtonCustom();
        jLabel3 = new javax.swing.JLabel();
        btnThem = new swing.Button();
        btnSua = new swing.Button();
        btnXoa = new swing.Button();
        btn_QLCT = new swing.Button();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblSanPham = new javax.swing.JTable();
        txtTimKiemSp = new textfield.TextField();
        button5 = new swing.Button();
        button6 = new swing.Button();

        setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setFont(new java.awt.Font("Segoe UI Variable", 1, 16)); // NOI18N
        jLabel1.setText("Thông Tin Sản Phẩm");

        jSeparator1.setForeground(new java.awt.Color(51, 51, 51));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(102, 102, 102)));

        txtMaSp.setLabelText("Mã Sản Phẩm");

        txtTenSp.setLabelText("Tên Sản Phẩm");

        txtMaVach.setLabelText("Mã Vạch");

        txtSoLuong.setLabelText("Số Lượng");

        txtGiaNhap.setLabelText("Giá Nhập");
        txtGiaNhap.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtGiaNhapActionPerformed(evt);
            }
        });

        txtGiaBan.setLabelText("Giá Bán");

        cboLoai.setLabeText("Loại");
        cboLoai.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cboLoaiActionPerformed(evt);
            }
        });

        cboSize.setLabeText("Size");

        cboChatLieu.setLabeText("Chất Liệu");

        cboNsx.setLabeText("Nhà Sản Xuất");

        cboMauSac.setLabeText("Màu Sắc");
        cboMauSac.setLightWeightPopupEnabled(false);

        jLabel2.setText("jLabel2");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, 154, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, 192, Short.MAX_VALUE)
                .addContainerGap())
        );

        txtMoTa.setLabelText("Mô Tả");
        txtMoTa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtMoTaActionPerformed(evt);
            }
        });

        buttonGroup1.add(rdoDangKD);
        rdoDangKD.setForeground(new java.awt.Color(51, 51, 51));
        rdoDangKD.setText("Ðang Kinh Doanh");
        rdoDangKD.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rdoDangKDActionPerformed(evt);
            }
        });

        buttonGroup1.add(rdoNgungKD);
        rdoNgungKD.setForeground(new java.awt.Color(51, 51, 51));
        rdoNgungKD.setText("Ngừng Kinh Doanh");

        jLabel3.setBackground(new java.awt.Color(204, 204, 204));
        jLabel3.setForeground(new java.awt.Color(153, 153, 153));
        jLabel3.setText("Trạng Thái");

        btnThem.setBackground(new java.awt.Color(102, 255, 102));
        btnThem.setForeground(new java.awt.Color(51, 51, 51));
        btnThem.setText("Thêm");
        btnThem.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N

        btnSua.setBackground(new java.awt.Color(255, 204, 0));
        btnSua.setForeground(new java.awt.Color(51, 51, 51));
        btnSua.setText("Sửa");
        btnSua.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N

        btnXoa.setBackground(new java.awt.Color(255, 51, 51));
        btnXoa.setForeground(new java.awt.Color(51, 51, 51));
        btnXoa.setText("Xóa");
        btnXoa.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N

        btn_QLCT.setBackground(new java.awt.Color(102, 153, 255));
        btn_QLCT.setForeground(new java.awt.Color(51, 51, 51));
        btn_QLCT.setText("Quản Lý Chi Tiết");
        btn_QLCT.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btn_QLCT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_QLCTActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(txtTenSp, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 190, Short.MAX_VALUE)
                    .addComponent(txtMaSp, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txtMaVach, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(txtGiaBan, javax.swing.GroupLayout.DEFAULT_SIZE, 190, Short.MAX_VALUE)
                        .addComponent(txtGiaNhap, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(txtSoLuong, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(cboChatLieu, javax.swing.GroupLayout.DEFAULT_SIZE, 190, Short.MAX_VALUE)
                            .addComponent(cboSize, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(cboNsx, javax.swing.GroupLayout.DEFAULT_SIZE, 190, Short.MAX_VALUE)
                            .addComponent(cboMauSac, javax.swing.GroupLayout.DEFAULT_SIZE, 190, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addComponent(txtMoTa, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(btnThem, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(btnSua, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(cboLoai, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGap(26, 26, 26)
                                .addComponent(jLabel3)))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(rdoDangKD, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(rdoNgungKD, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(btnXoa, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(btn_QLCT, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))))
                .addContainerGap(16, Short.MAX_VALUE))
        );

        jPanel1Layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {cboChatLieu, cboLoai, cboMauSac, cboNsx, cboSize, txtGiaBan, txtGiaNhap, txtMaSp, txtMaVach, txtSoLuong, txtTenSp});

        jPanel1Layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {btnSua, btnThem, btnXoa});

        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtMaSp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtGiaNhap, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cboChatLieu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cboMauSac, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtMoTa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtTenSp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtGiaBan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cboNsx, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cboSize, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtMaVach, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cboLoai, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtSoLuong, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(rdoDangKD, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(rdoNgungKD, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 16, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnSua, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnThem, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnXoa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_QLCT, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(16, 16, 16))
        );

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(102, 102, 102)));

        tblSanPham.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "STT", "Mã", "Tên Sản Phẩm", "Loại", "Size", "Chất Liệu", "Màu Sắc", "Nhà Sản Xuất", "Số Lượng", "Giá Nhập", "Giá Bán", "Mô Tả", "Ngày Thêm", "Trạng Thái"
            }
        ));
        tblSanPham.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblSanPhamMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblSanPham);

        txtTimKiemSp.setLabelText("Tìm Kiếm");

        button5.setBackground(new java.awt.Color(255, 204, 0));
        button5.setForeground(new java.awt.Color(51, 51, 51));
        button5.setText("Nhập File");
        button5.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N

        button6.setBackground(new java.awt.Color(102, 255, 102));
        button6.setForeground(new java.awt.Color(51, 51, 51));
        button6.setText("Xuất File");
        button6.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jScrollPane1)
                        .addContainerGap())
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(txtTimKiemSp, javax.swing.GroupLayout.PREFERRED_SIZE, 290, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(button6, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(button5, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(78, 78, 78))))
        );

        jPanel3Layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {button5, button6});

        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(button5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(button6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(txtTimKiemSp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 277, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel1)
                    .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void txtGiaNhapActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtGiaNhapActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtGiaNhapActionPerformed

    private void cboLoaiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cboLoaiActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cboLoaiActionPerformed

    private void txtMoTaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtMoTaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtMoTaActionPerformed

    private void rdoDangKDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rdoDangKDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rdoDangKDActionPerformed

    private void btn_QLCTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_QLCTActionPerformed

        QLCTDLog spDailog = new QLCTDLog(new javax.swing.JFrame(), true);
        spDailog.setVisible(true);
    }//GEN-LAST:event_btn_QLCTActionPerformed

    private void tblSanPhamMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblSanPhamMouseClicked
        clickTableSanPham();
    }//GEN-LAST:event_tblSanPhamMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private swing.Button btnSua;
    private swing.Button btnThem;
    private swing.Button btnXoa;
    private swing.Button btn_QLCT;
    private swing.Button button5;
    private swing.Button button6;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private combobox.Combobox cboChatLieu;
    private combobox.Combobox cboLoai;
    private combobox.Combobox cboMauSac;
    private combobox.Combobox cboNsx;
    private combobox.Combobox cboSize;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private radio_button.RadioButtonCustom rdoDangKD;
    private radio_button.RadioButtonCustom rdoNgungKD;
    private javax.swing.JTable tblSanPham;
    private textfield.TextField txtGiaBan;
    private textfield.TextField txtGiaNhap;
    private textfield.TextField txtMaSp;
    private textfield.TextField txtMaVach;
    private textfield.TextField txtMoTa;
    private textfield.TextField txtSoLuong;
    private textfield.TextField txtTenSp;
    private textfield.TextField txtTimKiemSp;
    // End of variables declaration//GEN-END:variables
}
